name: 'Pre-commit Composite Action'
description: 'Run pre-commit checks and handle changes'

inputs:
  py-version:
    description: 'Python version to use'
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3.2.2
      with:
        enable-cache: true

    - name: Install python
      shell: bash
      run: uv python install ${{ inputs.py-version }}

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ inputs.py-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      shell: bash
      run: uv run pre-commit run --all-files --show-diff-on-failure || true

    - name: Check for changes
      shell: bash
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit changes
      shell: bash
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m ":robot: Apply pre-commit changes"

    - name: Push changes
      shell: bash
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git push origin ${{ github.ref_name }}
