name: 🚀 Feature Request
description: Suggest a new feature or enhancement for gitmoji-pre-commit
title: "🚀 Feature: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.
  - type: textarea
    id: feature-description
    attributes:
      label: 💡 Feature Description
      description: Please describe the feature you would like to see
      placeholder: Describe the feature and its benefits
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: 🤔 Use Case
      description: Describe the use case for this feature
      placeholder: Explain how this feature would be used
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 💡 Motivation
      description: What is the motivation for this feature?
      placeholder: Explain why this feature is important. How did you get the idea?
  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions you've considered
  - type: checkboxes
    id: terms
    attributes:
      label: 📜 Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
