name: Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3.2.2
      with:
        enable-cache: true

    - name: Run tests
      run: uv run pytest
